# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

use_frameworks!

target 'FirebaseInstaClone' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for FirebaseInstaClone
  pod 'Netmera'
  
end


target 'FirebaseNotificationServiceExtension' do

  pod 'Netmera'

end

